# Generated by Django 3.0.8 on 2020-08-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('tipo_sanguineo', models.CharField(max_length=2)),
                ('fator_rh', models.BooleanField()),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('fumante', models.BooleanField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('sexo', models.BooleanField()),
                ('nome_mae', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=50)),
            ],
        ),
    ]
